//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int MaKhachHang { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> XepHangSao { get; set; }
        public string DanhGia { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
