//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuTruyCap
    {
        public int MaLichSu { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<bool> LoaiNguoiDung { get; set; }
        public string TenDangNhap { get; set; }
        public string IPAddress { get; set; }
        public string ThietBi { get; set; }
        public string TrinhDuyet { get; set; }
        public Nullable<System.DateTime> ThoiGianTruyCap { get; set; }
        public string HoatDong { get; set; }
    }
}
