//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienDangNhap
    {
        public int MaNhanVien { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public bool MatKhauTamThoi { get; set; }
        public string QuyenHan { get; set; }
        public bool VaiTro { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
